https://m.kugou.com/:
  song-info:    get                               app/i/getSongInfo.php?cmd=playInfo&from=mkugou&hash
  slider-src:   get:[].mod-slider>.swipe-wrap>div .#src=img!src&href=a!href
  songs-list:   get:[].panel-songslist%20li         .#id=!id&.panel-songs-item-name>span|innerText
  rank-list:    get:[].panel-img-list%20li          rank/list#href=a!href&src=img!_src&name=p|innerText&children=a!href:rank-info
  rank-info:    get:[].panel-songslist%20li         rank/info/:id#name=.panel-songs-item-name|innerText&id=!id
  plist-index:  get:[].panel-img-list%20li          plist/index#href=a!href&src=img!_src&name=p|innerText&count=.panel-img-content-sub|innerText&children=a!href:plist-list
  plist-list:   get:[].panel-songslist%20li         plist/list/:id#name=.panel-songs-item-name|innerText&id=!id
  search-hot:   get                               api/v3/search/hot?format=json&plat=0&count=30
  singer-class: get:[].bd%20li                    singer/class#href=a!href&children=a!href:singer-list&name=a|innerText&group=?parentNode
  singer-list:  get:[].singer-img-list>li         singer/list/:id#href=a!href&children=a!href:singer-info0\singer-info&imgurl=img!_src&name=p|innerText
  singer-info0: mget:[].singer-songs-list>li      singer/info/:id#hash=!id&singer=.singer-name|innerText&name=.song-name|innerText&data=em/innerText
  search:       get                               api/v3/search/song?format=json&page=1&pagesize=30&showtype=1
https://www.kugou.com/:
  singer-info:  cget:link[rel]+script       yy/singer/home/:id.html
http://efront.cc:5989/:
  all-dbs:     get                               _all_dbs
  add-db:      put                               :db_name
  del-db:      delete                            :db_name
  db-info:     get                               :name#data_size=sizes.active&disk_size=sizes.file
  del-item:    delete                            :type/:_id?rev
  add-item:    put                               :type/:_id
  add-site:    put                               grinch/:_id
  load-list:   post:docs                         :type/_find
  update-site: put                               grinch/:_id
  all-docs:    get                               :db_name/_all_docs?include_docs=true
  session:     xget                              _session
./:
  login:       xget                              api/login
  register:    xget                              api/register?:params