https://apiv2.pinduoduo.com/: 
  search-goods?keyword&page_info&sort_type: post api/jade/asics/search/goods_list # page_info:{current:1,page_size:10}

https://www.kugou.com/:
  singer-info:  cget:link[rel]+script       yy/singer/home/:id.html
http://efront.cc:5989/:
# http://localhost:5984/:
  all-dbs:     xget                               _all_dbs
  add-db:      xput                               :db_name
  del-db:      xdelete                            :db_name
  db-info:     xget                               :name#data_size=sizes.active&disk_size=sizes.file
  del-item:    xdelete                            :type/:_id?rev
  add-item:    xput                               :type/:_id
  add-site:    xput                               grinch/:_id
  load-list:   xpost:docs                         :type/_find
  update-site: xput                               grinch/:_id
  all-docs:    xget                               :db_name/_all_docs?include_docs=true
  session:     xget                              _session
  logout:      xdelete                           _session
./:
  login:       xget                              api/login
  register:    xget                              api/register?:params
http://efront.cc/:
  register:    xput                              /用户/
  login:       options                           ::login-:uid:::a
  load-list:   get                               /:type/:lastId,:size,:searchText                         :type/_find
  del-item:    delete                            /:type/:id
  add-item:    put                               /:type/:id
  update-item: post                              /:type/:id