- "name": 网络导航
  path: /page/grinch
  icon: fa fa-link
  data:
    type: grinch
  options:
    - icon: fa-plus
      name: 添加
      modal:
        path: "#/page/edit"
        actionId: add-site
        fields_ref: ./config/fields/site.yml
- icon: fa fa-retweet
  name: 工具
  children:
    - path: /grap/grap
      name: 静态分析
      data:
        searchtip: 输入完整的网址
- name: 设置
  icon: fa fa-setting
  roles:
    - hidden
  id: setting
  path: "#/user/setting"